const Images = {
    // slider1: require('./slider1.jpg'),
    // slider2: require('./slider2.jpg'),
    // slider3: require('./slider3.jpg'),
    // glass: require('./glass-right.png'),
    // shape1: require('./1.png'),
    // shape2: require('./2.png'),
    // shape3: require('./3.png'),
    // shape4: require('./4.png'),
    // shape5: require('./5.png'),
    // shape6: require('./6.png'),
    // shape7: require('./7.png'),
    // shape8: require('./8.png'),
    // shape9: require('./9.png'),
    // shape10: require('./10.png'),
    // shape11: require('./11.png'),
    // shape14: require('./14.png'),
    // shape15: require('./15.png'),
    // Features: require('./Features.png'),
    // bhanu: require('./bhanu.jpg'),
    // harsh: require('./harsh.jpg'),
    // osama: require('./osama.jpg'),
    // card1: require('./card-bg.jpg'),
    // FFhero: require('./FFHero.jpg'),
    // PJImg: require('./PJImg.jpg'),
    // s1: require('./s1.jpg'),
    // s2: require('./s2.jpg'),
    // s3: require('./s3.jpg'),
    // s4: require('./s4.jpg'),
    // logo1: require('./freelansters-logo1.png'),
    // logo: require('./freelansters-logo.png'),


}
export default Images;