const Cdata = [
    {
        id : "1",
        imgScr : "https://picsum.photos/200/130",
        title : "Gayming",
        date : "28/12/2002",
        content : "Sexii Boii",
    },
    {
        id : "2",
        imgScr : "https://picsum.photos/200/130",
        title : "Editing",
        date : "06/09/2006",
        content : "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "3",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "4",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "5",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "7",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "8",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "9",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "10",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "11",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "12",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "13",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "14",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "15",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "16",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },
    {
        id: "17",
        imgScr: "https://picsum.photos/200/130",
        title: "Editing",
        date: "06/09/2006",
        content: "Sax asperiores numquam deleniti ducimus alias quasi esse voluptas sed necessitatibus animi nesciunt, maxime perferendis dolorem. Aliquam!",
    },

]

export default Cdata;